Fix build with ASAN on Linux
I was getting the following error:

/usr/bin/ld: isle/3rdparty/SortFilterProxyModel/CMakeFiles/SortFilterProxyModel.dir/SortFilterProxyModel_autogen/mocs_compilation.cpp.o: relocation R_X86_64_PC32 against symbol `__asan_option_detect_stack_use_after_return' can not be used when making a shared object; recompile with -fPIC

And:

/home/mitch/dev/bgv/isle/3rdparty/SortFilterProxyModel/qqmlsortfilterproxymodel.cpp:1: error: In included file: "You must build your code with position independent code if Qt was configured with -reduce-relocations. "         "Compile your code with -fPIC (and not with -fPIE)."

Initially I fixed this with:

    set(CMAKE_POSITION_INDEPENDENT_CODE ON)

but was told the proper solution is to add the missing
target_link_libraries.